# Generated by Django 5.2.7 on 2025-10-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="senator_renewal_seats",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Bancas de senadores nacionales que se renuevan"
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="total_senators",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Total de senadoras y senadores del distrito"
            ),
        ),
    ]
