# Generated by Django 5.2.7 on 2025-10-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_district_senator_renewal_seats_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ["district__name", "order", "code"]},
        ),
        migrations.AddField(
            model_name="list",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Posición en la boleta o prioridad de exhibición"
            ),
        ),
    ]
