# Generated by Django 5.2.7 on 2025-10-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_alter_list_options_list_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ["district__name", "chamber", "order", "code"]},
        ),
        migrations.AlterUniqueTogether(
            name="list",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="list",
            name="chamber",
            field=models.CharField(
                choices=[("diputados", "Diputados"), ("senadores", "Senadores")],
                default="diputados",
                help_text="Cámara para la que se presenta la lista",
                max_length=15,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="list",
            unique_together={("district", "chamber", "code")},
        ),
    ]
