# Generated by Django 5.2.7 on 2025-10-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0004_alter_list_options_alter_list_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="national_alignment",
            field=models.CharField(
                blank=True,
                help_text="Denominación de la fuerza a nivel nacional",
                max_length=150,
            ),
        ),
    ]
